### ISSUE TITLE
DeprecationWarning in the latest version.

### ISSUE THREAD

**Issue by Walkeryr** [jackypan1989/del-webpack-plugin#7]
I'm using version 1.0.5 of del-webpack-plugin, during build I receive this warning: 
```
(node:64392) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at DelWebpackPlugin.apply (/Users/kyuri/project/node_modules/del-webpack-plugin/dist/index.js:33:16)
    at webpack (/Users/kyuri/project/node_modules/webpack/lib/webpack.js:37:12)
    at options.map.options (/Users/kyuri/project/node_modules/webpack/lib/webpack.js:28:55)
    at Array.map (<anonymous>)
    at webpack (/Users/kyuri/project/node_modules/webpack/lib/webpack.js:28:40)
    at Object.<anonymous> (/Users/kyuri/project/config/frontend/start.js:18:19)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
```

**Comment by jackypan1989** [comment]
This issue was already resolved. Please make sure your version.
https://github.com/jackypan1989/del-webpack-plugin/issues/5
